/**:
  ros__parameters:
    camera_name: "camera_3"
    frame_id: "camera_top/camera_link"
    pixel_format: rgb8
    serial_no: 224201677
    camera_info_url: "file:///home/ubuntu-mate/wong_lucid/src/lucid_vision_driver/config/camera_3fullres.yaml"
    fps: 15
    horizontal_binning: 4 # resize horizontal resolution/horizontal_binning
    vertical_binning: 4 # resize horizontal resolution/vertical_binning
    enable_rectifying: true
    enable_compressing: true
    use_default_device_settings: false
    # if you use_default_device_settings: true, the following settings are ignored.
    # ROS driver will use the default device settings of the camera.
    exposure_auto: false
    exposure_target: 65000
    gain_auto: false
    gain_target: 30
    gamma_target: 0.5
    image_horizontal_flip: true
    image_vertical_flip: true
    qos:
      reliability: "best effort"
      durability: "volatile"
      history: "keep_last"
      depth: 10


