/**:
  ros__parameters:
    camera_name: "camera_1"
    frame_id: "camera_top/camera_link"
    pixel_format: bgr8
    serial_no: 243401108
    camera_info_url: "/home/ubuntu-mate/wong_lucid/src/lucid_vision_driver/config/test_full_res.yaml"
    fps: 15
    horizontal_binning: 4 # resize horizontal resolution/horizontal_binning
    vertical_binning: 4 # resize horizontal resolution/vertical_binning
    enable_rectifying: true
    enable_compressing: true
    use_default_device_settings: true
    # if you use_default_device_settings: true, the following settings are ignored.
    # ROS driver will use the default device settings of the camera.
    exposure_auto: false
    exposure_target: 50000
    gain_auto: false
    gain_target: 40
    gamma_target: 0.4
    image_horizontal_flip: false
    image_vertical_flip: false


